//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudEmpleados
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatEmpresa
    {
        public CatEmpresa()
        {
            this.CatEmpleados = new HashSet<CatEmpleado>();
        }
    
        public int IdEmpresa { get; set; }
        public string RazonSocial { get; set; }
    
        public virtual ICollection<CatEmpleado> CatEmpleados { get; set; }
    }
}
